#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte <paultag@debian.org>, 2012 under the terms
# and conditions of the Expat license, a copy of which should be given to you
# with the source of this application.

from jinja2 import Environment, FileSystemLoader

import os.path
import json
import sys

env = Environment(loader=FileSystemLoader('templates'))
template = env.get_template(sys.argv[1])

def url_for(typ, **kwargs):
    base = {
        "static": "static",
    }
    if typ in base and "filename" in kwargs:
        return "%s/%s" % ( base[typ], kwargs['filename'] )
    else:
        raise Exception("Crappy type: %s" % ( typ ))

kwargs = {
    "url_for": url_for
}
context = "context.json"

if os.path.exists(context):
    kwargs.update(json.load(open(context, 'r')))

print template.render(**kwargs)
